mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('',include('web.urls',namespace='web')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .import views

app_name = 'web'

urlpatterns = [
    path('',views.home,name='home'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('search/',views.search,name='search'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('detail/<int:pk>/',views.product_detial,name='product_detial'),
    path('add-wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove-product/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),

]

templates/web/dashboard.html
{% extends 'base.html' %}
{% block title %} {{request.user.first_name}} User {% endblock %}
{% block content %}

<br>
<div class="container">
    <div class="row">
        {% for x in product %}

        <div class="card" style="width: 12rem; float: left; ">
            <div class="card-header" style="background-color: #343A40;"><span class="title">{{x.title}}</span>
            </div>
            <a href="{% url 'web:product_detial' pk=x.id %}">
                <img src="{{x.image.url}}" class="card-img-top">
            </a>
            <div class="card-body">
                <p class="card-text">{{x.description|truncatechars:50}}</p>
            </div>
            <div class="card-footer" style="background-color: #343A40;">
                <div class="title">
                    {{x.price}}
                    <span class="card-items">
                        <a href="{% url 'web:add_to_wishlist' pk=x.id %}">
                            <i class="fas fa-heart"></i>
                        </a>
                        <i class="fas fa-cart-plus"></i>
                    </span>
                </div>
            </div>
        </div>



        {% endfor %}
    </div>
</div>

{% endblock %}

templates/web/detail.html
{% extends 'base.html' %}
{% block title %} {{product.title}}{% endblock %}
{% block content %}

<br>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card detail-img-card">
                <div class="card-header">
                    <img class="detail-img" src="{{product.image.url}}" alt="">
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <span class="prod-desc">
                    {{product.title}}
                </span>
                <hr>
                <span class="detail-mrp">
                    MRP : <span id="mrp">1599.00</span>
                </span>

                <span class="detail-price">
                    Price : <span id="price">{{product.price}}</span>
                </span>

                <span class="detail-price">
                    You save : <span id="discount"></span>(<span id="dis-pcrtng"></span> %)
                </span>

                {{product.description}}

                
            </div>
            
        </div>
    </div>
</div>
<script>
console.log('MRP',document.getElementById('mrp').innerText);
console.log('Price',document.getElementById('price').innerText);
let mrp = document.getElementById('mrp').innerText;
let price = document.getElementById('price').innerText
let discount_value = document.getElementById('mrp').innerText - document.getElementById('price').innerText;
console.log('discount-value',discount_value);
document.getElementById('discount').innerText = discount_value;
discount_percentage = ((discount_value/mrp)*100);
document.getElementById('dis-pcrtng').innerText = Math.round(discount_percentage)
</script>
{% endblock %}

templates/web/wishlist.html
{% extends 'base.html' %}
{% block title %} {{request.user.first_name}} Wishlist {% endblock %}
{% block content %}
<br>
<div class="container">
    {% if not products %}
        nothing present in your wishlist
    {% else %}
  <div class="row">
    {% for x in products %}

    <div class="card" style="width: 12rem; float: left; ">
      <div class="card-header" style="background-color: #343A40;"><span class="title">{{x.title}}</span> </div>
      <img src="{{x.image.url}}" class="card-img-top">
      <div class="card-body">
        <p class="card-text">{{x.description|truncatechars:50}}</p>
      </div>
      <div class="card-footer" style="background-color: #343A40;">
        <div class="title">
          {{x.price}} 
          <span class="card-items">
            <a href="{% url 'web:remove_from_wishlist' pk=x.id %}">
                <i class="fas fa-heart-broken"></i>
            </a>
            <i class="fas fa-cart-plus"></i>
          </span>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
  {% endif %}
</div>

{% endblock %}