accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('register/complete/',views.register_complete,name='register_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('',include('web.urls',namespace='web')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .import views

app_name = 'web'

urlpatterns = [
    path('',views.home,name='home'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('search/',views.search,name='search'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('detail/<int:pk>/',views.product_detial,name='product_detial'),
    path('add-wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove-product/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/home.css' %}">
    <link rel="stylesheet" href="{% static 'web/detail.css' %}">
    <title>Ecomm : {% block title %}{% endblock %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" 
        href="{% if request.user.is_authenticated %}{% url 'web:dashboard' %}{% else %}{% url 'web:home' %}{% endif %}" 
        style="font-weight: bolder;">Ecomm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">


            <form class="form-inline my-2 my-lg-0" action="{% url 'web:search' %}" method="GET">
                <input class="form-control search-input mr-sm-2" type="search" name="query" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0 search-button" type="submit">Search</button>
            </form>
            <div class="header-item">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}"><span><i class="fas fa-user"></i></span>
                            Sign in</a>
                    </li>

                    {% else %}

                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><span><i class="fas fa-shopping-cart"></i></span> Cart</a>
                    </li>
                    <li class="nav-item dropdown" onclick="chk_category()" id="category-data">
                        <a class="nav-link dropdown-toggle" href="#" id="catedropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Category
                        </a>
                        <div class="dropdown-menu" aria-labelledby="catedropdown">
                            {% for x in category %}
                            <a class="dropdown-item" href="#">
                                {{x.name}}
                            </a>
                            {% endfor %}
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hello, {{request.user.first_name|capfirst}}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'web:wishlist' %}"><i class="fas fa-hand-holding-heart"></i>Wishlist</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </li>
                    {% endif %}


                </ul>
            </div>


        </div>
    </nav>


    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <!-- <script>
        function chk_category() {
            if ($('category-data').text().length === 0) {
                swal({
                    title: "Empty!",
                    text: "Their is no category in the list present!",
                    type: "warning"
                }).then(function () {
                    location.reload();
                });

            }
            else{
                pass
            }
        }



    </script> -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a28b225f4c.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Django Ecommerce Online Shop {% endblock %}
{% block content %}

{% endblock %}